diary/urls.py
from django.conf.urls import patterns, url


from diary import views

urlpatterns = patterns('',
	url(r'^$', views.index, name = 'index'),
	url(r'^login/$', views.login, name = 'login'),
	url(r'^logout/$', views.logout, name = 'logout'),
	url(r'^test/$', views.test, name = 'test'),	
	url(r'^register/$', views.register, name = 'register'),
	url(r'^profile/$', views.profile, name = 'profile'),
	url(r'^ajax/check_username/$', views.check_username, name = 'check_username'),
	url(r'^ajax/add_entry_photo/$', views.add_entry_photo, name = 'add_entry_photo'),
	url(r'^ajax/save_entry/$', views.save_entry, name = 'save_entry'),
	url(r'^entry/new/$', views.new_entry, name = 'new_entry'),
	url(r'^entry/delete/$', views.entry_delete, name = 'entry_delete'),
	url(r'^entry/(?P<entry_id>\d+)/$', views.entry, name = 'entry'),
	url(r'^entry/(?P<entry_id>\d+)/(?P<slug>[-\w]+)/$', views.entry, name = 'entry_slug'),
	url(r'^entry/edit/(?P<entry_id>\d+)/$', views.entry_edit, name = 'entry_edit'),
	url(r'^entry/edit/(?P<entry_id>\d+)/(?P<slug>[-\w]+)/$', views.entry_edit, name = 'entry_edit_slug'),
	#url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name = 'results'),
)

diaryexchange/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'diaryexchange.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('diary.urls', namespace = 'diary')),    
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

diary/models.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone

from unidecode import unidecode
from PIL import Image
from StringIO import StringIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import urllib
import os
import uuid

# Create your models here.
class Entry(models.Model):
	"""docstring for ClassName"""
	subject = models.CharField(max_length = 180)
	body = models.TextField()
	author = models.ForeignKey(User)
	slug = models.SlugField(max_length = 180)
	
	published = models.DateTimeField('Time Published', default= timezone.now)
	edited = models.DateTimeField('Time Edited', default=timezone.now)
	is_draft = models.BooleanField(default=True)

	

	def __unicode__(self):
		return self.subject


	def make_slug(self):
		""" create slug using self.subject """		
		sub = self.subject		
		if len(self.subject) == 0:
			self.subject = sub = "Untitled"
		sub = unidecode(sub)
		sub = slugify(sub)		
		self.slug = slugify(sub)

	def save(self,*args, **kwargs):				
		self.make_slug()		
		super(Entry, self).save(*args, **kwargs)	

		

	def update_last_edited_time(self):
		""" update edited field 
			short cut function for object update functions
		"""
		self.edited = timezone.now()

	def update_body(self, newBody):
		self.body = newBody
		self.update_last_edited_time()

	def update_subject(self, newSubject):
		self.subject = newSubject
		self.update_last_edited_time()

	#def remove_entry_photo(self,)

	def get_all_photoset_image_ids(self):
		photoset_ids = [photo.id for photo in self.entryphoto_set.all()]
		return photoset_ids

	def is_in_photoset(self, photoID):
		photo_set_ids = self.get_all_photoset_image_ids()
		if photoID in photo_set_ids:
			return True
		else:
			return False		

	#build a function that takes a list of entryphoto id, check if they are in this entry's entryphoto_set, if so, delete it.

	def delete_photoset_image(self,photoID):
		if self.is_in_photoset(photoID):
			image = self.entryphoto_set.get(pk = photoID)
			image_file = image.image_file

			storage = image_file.storage
			path = image_file.path

			storage.delete(path) #delete file
			image.delete() #delete record

			return True
		else:
			return False

	def remove_entry_photos_by_ids(self,photoIDs = []):
		"""
			delete entry photos from entryphoto_set with a list of IDs,
			if the photo with a passed ID is not part of the entryphoto_set,
			the photo will not be deleted.

			!! Make sure the IDs passed into this function are integer
		"""
		for photoID in photoIDs:
			if self.delete_photoset_image(photoID): #successfully deleted
				#print "EntryPhoto with Primary Key: %i is deleted" % photoID
				continue
			else:				
				#print 'Photo not in entryphoto_set, deletion failed'
				raise self.DoesNotExist				
				break	


	def filter_javascript_invalid(self,uploads,invalids):
		""" 
		Takes a list of uploaded item  and a list of invalid items reported by javascript
		return list of qualified items

		"""		
		cleaned_files = [] 		

		for item in uploads:					
			if item.name not in invalids: #only process js validated images on server to save resource										
				cleaned_files.append(item)

		return cleaned_files


	def process_entryphoto(self, image):
		""" 
		Takes an image file and validate, compress and convert it,
		returns the result.
		"""		
		if image.size/1024.0/1024 > 50: #MB
			return "Too Big", image.name
		
		acceptedPILFormat = ['JPEG','PNG','BMP','GIF']

		try:
			img = Image.open(image)
		except IOError:
			return "Cannot Open", image.name
		else:
			if img.format in acceptedPILFormat:
				img.thumbnail((1024,1024), Image.ANTIALIAS)
				imageString = StringIO()				
				if img.mode != 'RGB':
					name = ('temp.' + img.format).lower()
					img.save(imageString,format = img.format, optimize = True)
					imagefile = InMemoryUploadedFile(imageString, None, name, 'image/jpeg', imageString.len, None)					
				else:
					img.save(imageString,format = "JPEG", optimize = True)
					imagefile = InMemoryUploadedFile(imageString, None, 'temp_name.jpg', 'image/jpeg', imageString.len, None)
				#newPhoto = EntryPhoto.objects.create(image_file = imagefile, article = self)		
				return True, imagefile				
			else:
				return "Invalid Format", image.name 
		

	def add_entryphoto(self, images_list):		#not using this method to add photo anymore.
		invalid_image = 0
		for image in images_list:				
			if self.save_entryphoto(image):
				continue
			else:
				invalid_image += 1					
				#raise BaseException

		if invalid_image == 0:
			return 'all uploaded'

		return invalid_image

	def self_destruction(self):
		photoIDs = [image.id for image in self.entryphoto_set.all()]
		print photoIDs
		self.remove_entry_photos_by_ids(photoIDs)
		self.delete()


def uuid_filename(instance, filename):
	extension = filename.split('.')[-1] #get last piece
	filename = "%s.%s" % (uuid.uuid4().hex, extension)
	return os.path.join('entry_photo', filename)

class EntryPhoto(models.Model):
	article = models.ForeignKey(Entry)	
	image_file = models.ImageField(upload_to = uuid_filename)

class UserUploadedPhoto(models.Model):
	uploader = models.ForeignKey(User)
	image_file = models.ImageField(upload_to = uuid_filename)

	def __unicode__(self):
		return unicode(self.image_file.url)

diary/forms/diary_forms.py
from django import forms
from django.contrib.auth.models import User
from diary.models import Entry

class registerForm(forms.Form):	
	# TODO: Define form fields here
	username = forms.CharField(max_length = 20)
	email = forms.EmailField()
	password = forms.CharField(widget = forms.PasswordInput)
	confirm_password = forms.CharField(widget = forms.PasswordInput)	
	
	def clean_email(self):    	
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			#msg = forms.ValidationError('Email already used by another account.')
			#self.add_error('email', 'Email already used by another account.')
			raise forms.ValidationError('Email already used by another account.')
			
		return email

	def clean_password(self):
		password = self.cleaned_data['password']

		if len(password) < 8:
			raise forms.ValidationError('Password too short, 8 characters minimum.')
		return password


	def clean_confirm_password(self):
		password = self.cleaned_data.get('password', '')
		confirm_password = self.cleaned_data['confirm_password']

		if password == '':
			return

		if confirm_password != password:
			raise forms.ValidationError('Confirm password not matched')
		return confirm_password

class entryForm(forms.Form):
	subject = forms.CharField(max_length = 180)
	body = forms.CharField(widget = forms.Textarea)
	# class Meta:
	# 	model = Entry
	# 	fields = ['subject', 'body', 'author']	

	# def clean_subject(self): #this works
	# 	subject = self.cleaned_data['subject']
	# 	if  subject != "hello world":
	# 		raise forms.ValidationError('You need to say hello to the world in your subject')
	# 	return subject	  

diary/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, Http404, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import auth 
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from datetime import datetime
from diary.models import Entry, EntryPhoto, UserUploadedPhoto
from diary.forms.diary_forms import registerForm
from PIL import Image

import os, sys
# Create your views here.


def login(request):
	nextPage = '/' #just to be safe

	if request.method == "POST":
		un = request.POST['login_username']
		pw = request.POST['login_password']		
		user = authenticate(username = un, password = pw)
		nextPage = request.GET.get('next',"/")

		if user != None:
			auth.login(request, user)
			if nextPage == '/':
				messages.success(request, 'Logged in')
				return redirect('diary:index')				
			else:				
				# messages.info(request, 'Redirecting you to the previous page')
				return redirect(nextPage)				

		else:		
			return render(request, 'diary/login.html', {'message': 'Login Failed'})	

	if request.GET:
		nextPage = request.GET.get("next",'/')

	return render(request, 'diary/login.html', {'next': nextPage})


def register(request):

	form = registerForm()

	if request.method == 'POST':
		form = registerForm(request.POST)
		if form.is_valid():			
			data = form.cleaned_data
			messages.info(request, "The form is valid %s" % data)			
			return redirect('diary:register')				
	return render(request, 'diary/register.html', {'form' : form})


@login_required
def logout(request):	
	auth.logout(request)	
	return redirect('diary:login')


@login_required
def index(request):		
	# messages.info(request, request.META.get('HTTP_REFERER', ""))
	entries = Entry.objects.filter(is_draft = False).filter(published__lte = timezone.now()).order_by('-published')			
	return render(request, 'diary/index.html', {'entries': entries})


@login_required
def new_entry(request):
	if request.method == "GET":		
		#request.session['current_entry'] = None
		return render(request, 'diary/new_entry.html', {'years': range(1991, datetime.now().year)})

	elif request.method == "POST":				
		entry = None

		try:
			entry = Entry.objects.get(pk = request.POST.get('entry-id'))
		except:
			entry = Entry()		

		entry.subject = request.POST.get('subject', "")
		entry.body = request.POST.get('body', "")
		entry.author = request.user
		entry.is_draft = False #need to set this to make it publicly available
		entry.published = datetime.fromtimestamp(int(request.POST.get('timestamp', datetime.now().strftime('%s'))))		
		entry.save()				

		return redirect('diary:entry_slug', entry_id = int(entry.id), slug = str(entry.slug))		

	else:
		raise Http404
		
		
@login_required
def save_entry(request):
	""" This view process entry saving POSTed by Ajax
		The Ajax call is triggered when the user changed the content of a post,
		then idled for 3 seconds.

		Note: Only JavaScript checking is implemented, need to set timeout on
		server side as well in the future to lower the threat of DDoS attack.
	"""
	if request.method == "POST" and request.is_ajax():	
		entry = None
		subject = request.POST.get('subject', "")
		body = request.POST.get('body', "")

		if request.POST.get('current_entry', "false") == "false": #new entry
			entry = Entry.objects.create(subject = subject, body = body, author = request.user)			
			return HttpResponse(entry.id)	 

		else: #update entry		
			entry = Entry.objects.get(pk = request.POST.get('current_entry'))
			if entry.subject != subject:
				entry.subject = subject				
			if entry.body != body:
				entry.body = body				
			entry.edited = timezone.now()
			entry.save()			
			return HttpResponse(entry.id)	 					
	else:
		raise Http404		

@login_required
def entry(request, entry_id, **slug):
	""" 
		Slug is an optional keyword argument when parsing the url pattern in urls.py
		this view function means that the url can be simply foo.com/entry_id
		or foo.com/entry_id/slug
		where entry_id is required in both cases in order to avoid url clashing
		(slug might not be unique in all entries)
	"""
	entry = get_object_or_404(Entry, pk = entry_id)		
	if slug and slug.get('slug') != entry.slug:
		raise Http404

	if entry.published > timezone.now() and request.user != entry.author:
		raise Http404	
	
	return render(request, 'diary/entry.html', {'entry': entry})


@login_required
def entry_delete(request):
	error_message = ""
	if request.method == 'POST':
		try:
			entry = Entry.objects.get(pk = request.POST.get('entry-id'))			
			if request.user == entry.author:
				entry.self_destruction()
				return redirect('diary:index')
			else:
				error_message = "Error: Entries can only be deleted by the author."
		except:
			error_message = "Error: Entry does not exist."		

		response = render(request, 'base.html', {'error_message': error_message})
		return HttpResponseBadRequest(response)
	else:
		raise Http404


@login_required
def entry_edit(request, entry_id, **slug):
	entry = get_object_or_404(Entry, pk=entry_id)	
	if slug and slug.get('slug') != entry.slug: #slug in url should match entry's slug		
		raise Http404
	if request.user != entry.author:
		messages.info(request, 'Entries can only be edited by the author.')
		return redirect(request.META.get('HTTP_REFERER', "/"))

	#safe to assume below the user is the author, the id and slug used in URL matched an entry

	if request.method == "GET":
		return render(request, 'diary/entry_edit.html', {'entry': entry})		

	if request.method == 'POST':		
		#handle subject and body change, edited time is updated if changes presence
		sub = request.POST.get('subject', entry.subject)
		bod = request.POST.get('body', entry.body)		

		if sub != entry.subject:
			entry.update_subject(sub) #renew update time
		if bod != entry.body:
			entry.update_body(bod)

		if request.POST.get('timestamp', "") != "":
			try:
				entry.published = datetime.fromtimestamp(int(request.POST.get('timestamp',""))) 
			except:
				#if anything goes wrong, use original published time.
				entry.published = datetime.fromtimestamp(int(entry.published.strftime('%s'))) 

		save_as_draft = request.POST.get('is_draft', False)
		
		if save_as_draft == 'True':
			entry.is_draft = True #need to set this to make it publicly available			
		else:
			entry.is_draft = False		
		
		entry.save() #changed or not, save it.
		return redirect('diary:entry_slug', entry_id = int(entry.id), slug = str(entry.slug) ) #go to entry after update	


def check_username(request):	

	if request.method == 'GET' and request.is_ajax():		
		if request.GET.get('username',None):
			username = request.GET['username']
			try:
				used = User.objects.get(username = username)
				used = True
			except User.DoesNotExist:
				used = False								
			return HttpResponse(used) 
		else:
			return HttpResponse('No Valid Data Submitted by Ajax') 
	else:
		response = render(request, 'base.html', { "error_message": "Nothing to see here, please move along :P"} )
		return HttpResponseBadRequest(response)
		#raise Http404
		#return redirect('diary:index')

@login_required
def add_entry_photo(request):	
	if request.method == 'POST' and request.is_ajax():
		entry = None
		try:
			entry = Entry.objects.get(pk = request.POST.get('entry_id',None))
		except:
			return HttpResponseBadRequest('Error: Cannot attach entry photo to a valid entry.')		

		if entry.author != request.user:
			return HttpResponseBadRequest('Error: Only the author may update/edit an entry.')					

		if request.FILES and len(request.FILES) == 1:			
			result = entry.process_entryphoto(request.FILES['photo'])
			if result[0] == True: #safe to save as photo
				photo = EntryPhoto.objects.create(article = entry, image_file = result[1])
				return HttpResponse(photo.image_file.url)				
			else:					
				return HttpResponse("Error: Failed")				
		else:
			return HttpResponseBadRequest('Error: Cannot process more than 1 photo at a time.')			
	else:
		raise Http404

def test(request):
	message = "You're at test page"
	message = ""
	filelist = []
	for filename in os.listdir('./media/compressed'):
		filelist.append(filename)
		#message += "<img src = >" + filename + "</p>"
	
	#return HttpResponse(message)
	return render(request, 'diary/test.html', {'files': filelist})


@login_required
def profile(request):
	entries = request.user.entry_set.all().order_by('-published')
	return render(request, 'diary/profile.html', {'entries': entries})

diary/templates/diary/entry.html
{% extends 'base.html' %}

{% block css %}
	<style type="text/css">
		.meta-data {
			color: #888;
		}

		p {
			color: #444;
		}
		
		img.entry-photo {
			max-width: 100%;			
			margin-top: 1.5em;
		}

		img.entry-photo:last-child {
			margin-bottom: 2em;
		}
	</style>
{% endblock css %}

{% block content %}
	{% if entry%}
	<div class = 'entry break-words'>
		<h2>{{ entry.subject }}</h2>
		<p class = 'meta-data'>Posted by: {{ entry.author.first_name }} at {{ entry.published }} | Last Edited: {{ entry.edited }}  {% if user == entry.author %}<a href="{% url 'diary:entry_edit_slug' entry.id entry.slug %}">edit</a>{% endif %}</p>
		
		{# <h1>{{ user }}</h1> #}
		{# <p>{{ entry.author }}</p> #}
		<p>{{ entry.body|safe|linebreaks }}</p>		
	</div>
	{% else %}
		<h1>Invalid Entry - No data to show</h1>
	{% endif %}
	{% comment %}
	{% if entry_photos %}
		{% for image in entry_photos %}
			<a target = "_blank" href = '{{image.image_file.url}}' title = 'Open in new tab'><img class = 'entry-photo' src="{{ image.image_file.url }}"></a>
			
		{% endfor %}
	{% endif %}
	{% endcomment %}

{% endblock content%}

diary/templates/diary/entry_edit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" type="text/css" href='//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css'>
	<link rel="stylesheet" type="text/css" href='{% static "library/summernote/summernote.css" %}'>
	<link rel="stylesheet" type="text/css" href="{% static 'library/rome-date/rome.min.css' %}">
	<style type="text/css">
		.form-control, .btn {
			border-radius: 0;
			margin-top: 1em;
		}

		#time-picker {
			display: none;
		}

		.rd-container th {
			padding: 4px;
		}

		input[name='subject'] {
			margin-bottom: 1em;
		}

		.note-editable {
			background-color: white;
		}		

		img {
			width: 100%;
			margin-top: 1em;
		}

		img.half-size {
			width: 50%;
		}

		textarea {
			min-height: 20em;
			max-width: 100%;
			resize: none;
		}		

	</style>
{% endblock css %}

{% block content %}	
	{# <iframe src="{% url 'diary:test' %}" width = '100%'></iframe> #}
	{% if entry %}
		<p><a id = 'toggle-time-picker'>Set Publish Date</a></p>
		<div class = 'row' id = 'time-picker'>
			<div class = 'col-md-6'>
				<input class = 'form-control' id = 'date' name = 'datetimepicker' placeholder = 'Publish Date (Blank for today)'>	
			</div>
			<div class = 'col-md-6'>
				<input class = 'form-control' id = 'time' name = 'datetimepicker' placeholder = 'Publish Time (Blank for Midnight)'>					
			</div>
			<div class = 'col-md-12'>
				<div class = 'btn btn-success' id = 'set-time'>Set</div>				
			</div>
		</div>
		<form id = 'edit-entry-form' action = "{% url 'diary:entry_edit' entry.id %}" method = 'post' enctype="multipart/form-data">
			{% csrf_token %}
			<input class = 'form-control' type = 'text' name = 'subject' value = '{{ entry.subject }}' autocomplete = 'off'>
			<p id = 'publish-time'></p>
			<div id = 'summernote'></div>
			<textarea class = 'form-control' name = 'body'>{{ entry.body }}</textarea>		
			<input type = 'hidden' value = 'False' name = 'entry-delete'>
			
			<input class = 'form-control' type = 'hidden' placeholder = 'Selected Photo' name = 'selected-entry-photo'>
			{# <input class = 'form-control' type = 'file' name = 'new-entry-photo' id = "multi" multiple> #}
			<input type = 'hidden' name = "invalid-images">			
			<input id = 'final-date' name = 'timestamp' type = 'hidden'>

			<div style = 'text-align: right'><a class = 'fake-link' id = 'save-as-draft'><p>{% if entry.is_draft == True %}Update Without Publishing{% else %}Revert to draft{% endif %}</p></a>
			<input type = 'hidden' name = 'is_draft'>

			<div class = 'row'>
				<div class = 'col-md-6'>
					<div id = 'delete-entry' class = 'btn btn-danger btn-block'>Delete</div>
				</div>
				<div class = 'col-md-6'>
					<input type = 'submit' value = 'Update & Publish' class = 'btn btn-warning btn-block'>
				</div>
			</div>
		</form>
		<form id = 'delete-entry-form' action = "{% url 'diary:entry_delete' %}" method = "post">
			{% csrf_token %}
			{# ID is required because this form will be posted to another view and handled #}
			<input name = 'entry-id' type = 'hidden' value = "{{ entry.id }}">			
		</form>


	{% else %}
		<h1>This is edit entry page</h1>
	{% endif %}

	

{% endblock content %}

{% block script %}	
	<script type="text/javascript" src = '{% static "library/autosize/jquery.autosize.min.js" %}'></script>	
	<script type="text/javascript" src = '{% static "library/summernote/summernote.min.js" %}'></script>	
	<script type="text/javascript" src = '{% static "library/moment.min.js" %}'></script>	
	<script type="text/javascript" src = '{% static "library/rome-date/rome.min.js" %}'></script>	
	<script type="text/javascript" src = '{% static "js/entry-editor.js" %}'></script>

	<script type="text/javascript">
		$(document).ready(function(){				
			summernote.code($('textarea[name="body"]').val())
			$('textarea[name="body"]').hide();

			currentEntry = $('input[name="entry-id"]').val()			

			$('#delete-entry').click(function(){
				var delEntry = confirm('Delete this diary entry?')				
				if (delEntry) {					
					$('#delete-entry-form').submit()										
				}				
			})

			$('input[type="submit"]').click(function(e){
				e.preventDefault()					
				/*if ($('#final-date').val() == ""){
					//fillPublishTimestamp()
					$('#final-date').val('asd')
				}*/
				var sub = $('input[name = "subject"]').val()
				var bod = $('textarea[name = "body"]').val()								
				if (sub.length == 0 && bod.length == 0) {
					var submitEmptyEntry = confirm("You're about to publish an empty entry, is it ok?")
					if (!submitEmptyEntry){
						return
					}
				}		
				$('#edit-entry-form').submit();
			})			

			$('#edit-entry-form textarea').focus(function(){
				$(this).autosize();
			})
			var pDate = rome(date, {
				weekStart: 1,
				time: false,	
			})		

			var pTime = rome(time, {			
				date: false,	
			})		

			var dateTimeToTimestamp = function(date, time){
				// date format 2015-01-27
				// time format 13:15:55
				timestamp = date + " " + time
				timestamp = moment(timestamp).unix()		
				return timestamp
			}

			var fillPublishTimestamp = function(){
				var dateStamp = moment().format('YYYY-MM-DD')
				var timeStamp = moment().format('HH:mm:ss')
				

				if (pTime.getDate() != null) {
					timeStamp = $('#time').val()			
				}		

				if (pDate.getDate() != null) {
					dateStamp = $('#date').val()			
					if (pTime.getDate() == null) {
						timeStamp = "00:00:00"
					}
				}		
				readableTime = moment(dateStamp + " " + timeStamp).calendar()
				$('#final-date').val(dateTimeToTimestamp(dateStamp, timeStamp))		
				return readableTime		
			}

			$('#toggle-time-picker').click(function(){
				$('#publish-time').text('')
				$(this).hide(function(){
					$('#time-picker').show()					
				})
			})

			$('#set-time').click(function(){
				$('#publish-time').text("Publish Date: " + fillPublishTimestamp());
				$('#toggle-time-picker').text('Change Publish Date');		
				$('#time-picker').hide();
				$('#toggle-time-picker').show();		
			})

			$('#save-as-draft').click(function(){				
				$('input[name="is_draft"]').val('True')
				$('input[type="submit"]').click()
			})
		})

	</script>

{% endblock script %}

diary/templates/diary/entry_model.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load diary_filters %}

{% block content %}
	{% if form %}
		{{ form.subject.label_tag }}
		{{ form.subject|attr:"class:form-control" }}
		{{ form.subject.label_tag }}
		{{ form.subject|attr:"class:form-control" }}
	{% endif %}
{% endblock content %}

diary/templates/diary/index.html
{% extends 'base.html' %}

{% block css %}

	<style type="text/css">
		#entries a {
			color: #F37074;			
		}

		img {
			width: 100%;
		}
		
	</style>

{% endblock css %}

{% block content %}
	<span id = 'entries'> 
	{% for entry in entries %}
	<div class = 'entry-summary break-words'>
		<h1><a href="{% url 'diary:entry_slug' entry.id entry.slug  %}">{{ entry.subject }}</a></h1>
		<p>{{ entry.body|safe|linebreaks|truncatechars:300 }}</p>				
	</div>
	{% endfor %}
	</span>
	{# {{ message|safe }} #}
	

{% endblock content %}

diary/templates/diary/login.html
{% extends 'base.html' %}

{% block css %}

	<style type="text/css">
		#login-form input{
			margin-top: 1em;
		}

		#login-form input[type='submit']{
			margin-bottom: 1em;
		}

		#login-form-wrapper {
			background-color: #EDF0F1;
			border-radius: 0.5em;
			border: 1px solid #688E92;
		}

	</style>

{% endblock css %}


{% block content %}
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<h1{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h1>
			{% endfor %}
		</ul>
	{% endif %}						
	
	<div class = 'col-md-8 col-md-offset-2' id = 'login-form-wrapper'>
		<form action = "{% url 'diary:login' %}?next={{next}}" method="post" id = 'login-form'>
			{% csrf_token %}
			<input type = 'text' name = 'login_username' placeholder = 'Username' class = 'form-control'>
			<input type = 'password' name = 'login_password' placeholder = 'Password' class = 'form-control'>
			<input type = 'submit' value = 'Login' class = 'btn btn-success center-block'>
		</form>
	</div>	


{% endblock content %}